version: '3.4'

volumes:
  local_postgres_data: {}

services:
  formmanager.api:
    image: ${DOCKER_REGISTRY-}formmanagerapi
    build:
      context: .
      dockerfile: FormManager/Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data