<template>
  <div class="loadingio-spinner-dual-ring-y8acm4vwlgi">
    <div class="ldio-t1rngx88p7e">
      <div></div>
      <div>
        <div></div>
      </div>
    </div>
  </div>

</template>

<script>
export default {
  name: "Loader"
}
</script>

<style scoped>
@keyframes ldio-t1rngx88p7e {
  0% {
    transform: rotate(0)
  }
  100% {
    transform: rotate(360deg)
  }
}

.ldio-t1rngx88p7e div {
  box-sizing: border-box !important
}

.ldio-t1rngx88p7e > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #1d0e0b transparent #1d0e0b transparent;
  animation: ldio-t1rngx88p7e 1s linear infinite;
}

.ldio-t1rngx88p7e > div:nth-child(2) {
  border-color: transparent
}

.ldio-t1rngx88p7e > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}

.ldio-t1rngx88p7e > div:nth-child(2) div:before, .ldio-t1rngx88p7e > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #1d0e0b;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #1d0e0b;
}

.ldio-t1rngx88p7e > div:nth-child(2) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #1d0e0b;
}

.loadingio-spinner-dual-ring-y8acm4vwlgi {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

}

.ldio-t1rngx88p7e {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}

.ldio-t1rngx88p7e div {
  box-sizing: content-box;
}

/* generated by https://loading.io/ */
</style>